// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: user_enter.proto

package user_enter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserEnterRegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UserEnterRegisterRequest) Reset() {
	*x = UserEnterRegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_enter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserEnterRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEnterRegisterRequest) ProtoMessage() {}

func (x *UserEnterRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_enter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEnterRegisterRequest.ProtoReflect.Descriptor instead.
func (*UserEnterRegisterRequest) Descriptor() ([]byte, []int) {
	return file_user_enter_proto_rawDescGZIP(), []int{0}
}

func (x *UserEnterRegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UserEnterRegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserEnterId int64 `protobuf:"varint,1,opt,name=UserEnterId,proto3" json:"UserEnterId,omitempty"`
}

func (x *UserEnterRegisterResponse) Reset() {
	*x = UserEnterRegisterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_enter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserEnterRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEnterRegisterResponse) ProtoMessage() {}

func (x *UserEnterRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_enter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEnterRegisterResponse.ProtoReflect.Descriptor instead.
func (*UserEnterRegisterResponse) Descriptor() ([]byte, []int) {
	return file_user_enter_proto_rawDescGZIP(), []int{1}
}

func (x *UserEnterRegisterResponse) GetUserEnterId() int64 {
	if x != nil {
		return x.UserEnterId
	}
	return 0
}

var File_user_enter_proto protoreflect.FileDescriptor

var file_user_enter_proto_rawDesc = []byte{
	0x0a, 0x10, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x22, 0x2e,
	0x0a, 0x18, 0x55, 0x73, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3d,
	0x0a, 0x19, 0x55, 0x73, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x55,
	0x73, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x49, 0x64, 0x32, 0x6d, 0x0a,
	0x09, 0x55, 0x73, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x60, 0x0a, 0x11, 0x55, 0x73,
	0x65, 0x72, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12,
	0x24, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x65, 0x6e, 0x74,
	0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0e, 0x5a, 0x0c,
	0x2e, 0x3b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_enter_proto_rawDescOnce sync.Once
	file_user_enter_proto_rawDescData = file_user_enter_proto_rawDesc
)

func file_user_enter_proto_rawDescGZIP() []byte {
	file_user_enter_proto_rawDescOnce.Do(func() {
		file_user_enter_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_enter_proto_rawDescData)
	})
	return file_user_enter_proto_rawDescData
}

var file_user_enter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_enter_proto_goTypes = []any{
	(*UserEnterRegisterRequest)(nil),  // 0: user_enter.UserEnterRegisterRequest
	(*UserEnterRegisterResponse)(nil), // 1: user_enter.UserEnterRegisterResponse
}
var file_user_enter_proto_depIdxs = []int32{
	0, // 0: user_enter.UserEnter.UserEnterRegister:input_type -> user_enter.UserEnterRegisterRequest
	1, // 1: user_enter.UserEnter.UserEnterRegister:output_type -> user_enter.UserEnterRegisterResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_enter_proto_init() }
func file_user_enter_proto_init() {
	if File_user_enter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_enter_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*UserEnterRegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_enter_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*UserEnterRegisterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_enter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_enter_proto_goTypes,
		DependencyIndexes: file_user_enter_proto_depIdxs,
		MessageInfos:      file_user_enter_proto_msgTypes,
	}.Build()
	File_user_enter_proto = out.File
	file_user_enter_proto_rawDesc = nil
	file_user_enter_proto_goTypes = nil
	file_user_enter_proto_depIdxs = nil
}
