// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: distribution.proto

package distribution

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LookDoneOrUpReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *LookDoneOrUpReq) Reset() {
	*x = LookDoneOrUpReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distribution_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookDoneOrUpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookDoneOrUpReq) ProtoMessage() {}

func (x *LookDoneOrUpReq) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookDoneOrUpReq.ProtoReflect.Descriptor instead.
func (*LookDoneOrUpReq) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{0}
}

func (x *LookDoneOrUpReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LookDoneOrUpResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*UserList `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *LookDoneOrUpResp) Reset() {
	*x = LookDoneOrUpResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distribution_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookDoneOrUpResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookDoneOrUpResp) ProtoMessage() {}

func (x *LookDoneOrUpResp) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookDoneOrUpResp.ProtoReflect.Descriptor instead.
func (*LookDoneOrUpResp) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{1}
}

func (x *LookDoneOrUpResp) GetList() []*UserList {
	if x != nil {
		return x.List
	}
	return nil
}

type UserList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid        uint32 `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`               //用户id
	Account    string `protobuf:"bytes,2,opt,name=Account,proto3" json:"Account,omitempty"`        //用户账号
	SpreadUid  uint32 `protobuf:"varint,3,opt,name=SpreadUid,proto3" json:"SpreadUid,omitempty"`   //推广元id
	UserType   string `protobuf:"bytes,4,opt,name=UserType,proto3" json:"UserType,omitempty"`      //用户类型
	IsPromoter int64  `protobuf:"varint,5,opt,name=IsPromoter,proto3" json:"IsPromoter,omitempty"` //是否为推广员
}

func (x *UserList) Reset() {
	*x = UserList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distribution_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserList) ProtoMessage() {}

func (x *UserList) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserList.ProtoReflect.Descriptor instead.
func (*UserList) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{2}
}

func (x *UserList) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserList) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *UserList) GetSpreadUid() uint32 {
	if x != nil {
		return x.SpreadUid
	}
	return 0
}

func (x *UserList) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

func (x *UserList) GetIsPromoter() int64 {
	if x != nil {
		return x.IsPromoter
	}
	return 0
}

type TheChartsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TheChartsRequest) Reset() {
	*x = TheChartsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distribution_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TheChartsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TheChartsRequest) ProtoMessage() {}

func (x *TheChartsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TheChartsRequest.ProtoReflect.Descriptor instead.
func (*TheChartsRequest) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{3}
}

type TheChartsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*ListRank `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *TheChartsResponse) Reset() {
	*x = TheChartsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distribution_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TheChartsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TheChartsResponse) ProtoMessage() {}

func (x *TheChartsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TheChartsResponse.ProtoReflect.Descriptor instead.
func (*TheChartsResponse) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{4}
}

func (x *TheChartsResponse) GetList() []*ListRank {
	if x != nil {
		return x.List
	}
	return nil
}

type ListRank struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToUserId int64   `protobuf:"varint,1,opt,name=ToUserId,proto3" json:"ToUserId,omitempty"`
	Amount   float32 `protobuf:"fixed32,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
}

func (x *ListRank) Reset() {
	*x = ListRank{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distribution_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRank) ProtoMessage() {}

func (x *ListRank) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRank.ProtoReflect.Descriptor instead.
func (*ListRank) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{5}
}

func (x *ListRank) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *ListRank) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// 分销等级设置
type DistributionLevelSettingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Img       string  `protobuf:"bytes,5,opt,name=img,proto3" json:"img,omitempty"`             //图片
	LevelName string  `protobuf:"bytes,1,opt,name=LevelName,proto3" json:"LevelName,omitempty"` //等级名称
	Level     int64   `protobuf:"varint,2,opt,name=Level,proto3" json:"Level,omitempty"`        //等级
	One       float32 `protobuf:"fixed32,3,opt,name=One,proto3" json:"One,omitempty"`           //一级返佣比例
	Two       float32 `protobuf:"fixed32,4,opt,name=Two,proto3" json:"Two,omitempty"`           //二级返佣比例
}

func (x *DistributionLevelSettingRequest) Reset() {
	*x = DistributionLevelSettingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distribution_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DistributionLevelSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistributionLevelSettingRequest) ProtoMessage() {}

func (x *DistributionLevelSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistributionLevelSettingRequest.ProtoReflect.Descriptor instead.
func (*DistributionLevelSettingRequest) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{6}
}

func (x *DistributionLevelSettingRequest) GetImg() string {
	if x != nil {
		return x.Img
	}
	return ""
}

func (x *DistributionLevelSettingRequest) GetLevelName() string {
	if x != nil {
		return x.LevelName
	}
	return ""
}

func (x *DistributionLevelSettingRequest) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *DistributionLevelSettingRequest) GetOne() float32 {
	if x != nil {
		return x.One
	}
	return 0
}

func (x *DistributionLevelSettingRequest) GetTwo() float32 {
	if x != nil {
		return x.Two
	}
	return 0
}

type DistributionLevelSettingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DistributionLevelSettingResponse) Reset() {
	*x = DistributionLevelSettingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distribution_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DistributionLevelSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistributionLevelSettingResponse) ProtoMessage() {}

func (x *DistributionLevelSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistributionLevelSettingResponse.ProtoReflect.Descriptor instead.
func (*DistributionLevelSettingResponse) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{7}
}

func (x *DistributionLevelSettingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 生成邀请码
type GenerateInvitationCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"` //用户id，中间件获取
	Type   int64 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`     //邀请码类型
}

func (x *GenerateInvitationCodeRequest) Reset() {
	*x = GenerateInvitationCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distribution_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateInvitationCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateInvitationCodeRequest) ProtoMessage() {}

func (x *GenerateInvitationCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateInvitationCodeRequest.ProtoReflect.Descriptor instead.
func (*GenerateInvitationCodeRequest) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{8}
}

func (x *GenerateInvitationCodeRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GenerateInvitationCodeRequest) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

type GenerateInvitationCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=Url,proto3" json:"Url,omitempty"`
}

func (x *GenerateInvitationCodeResponse) Reset() {
	*x = GenerateInvitationCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distribution_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateInvitationCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateInvitationCodeResponse) ProtoMessage() {}

func (x *GenerateInvitationCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateInvitationCodeResponse.ProtoReflect.Descriptor instead.
func (*GenerateInvitationCodeResponse) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{9}
}

func (x *GenerateInvitationCodeResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// 用户填写邀请码
type UserFillsInInvitationCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint32 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"` //用户id，中间件获取
	Str    string `protobuf:"bytes,2,opt,name=Str,proto3" json:"Str,omitempty"`        //邀请码
}

func (x *UserFillsInInvitationCodeRequest) Reset() {
	*x = UserFillsInInvitationCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distribution_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserFillsInInvitationCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFillsInInvitationCodeRequest) ProtoMessage() {}

func (x *UserFillsInInvitationCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFillsInInvitationCodeRequest.ProtoReflect.Descriptor instead.
func (*UserFillsInInvitationCodeRequest) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{10}
}

func (x *UserFillsInInvitationCodeRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserFillsInInvitationCodeRequest) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

type UserFillsInInvitationCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success string `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UserFillsInInvitationCodeResponse) Reset() {
	*x = UserFillsInInvitationCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distribution_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserFillsInInvitationCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFillsInInvitationCodeResponse) ProtoMessage() {}

func (x *UserFillsInInvitationCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFillsInInvitationCodeResponse.ProtoReflect.Descriptor instead.
func (*UserFillsInInvitationCodeResponse) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{11}
}

func (x *UserFillsInInvitationCodeResponse) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

var File_distribution_proto protoreflect.FileDescriptor

var file_distribution_proto_rawDesc = []byte{
	0x0a, 0x12, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x22, 0x21, 0x0a,
	0x0f, 0x4c, 0x6f, 0x6f, 0x6b, 0x44, 0x6f, 0x6e, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x52, 0x65, 0x71,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64,
	0x22, 0x39, 0x0a, 0x10, 0x4c, 0x6f, 0x6f, 0x6b, 0x44, 0x6f, 0x6e, 0x65, 0x4f, 0x72, 0x55, 0x70,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x25, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x90, 0x01, 0x0a, 0x08,
	0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x55, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x70, 0x72, 0x65, 0x61, 0x64, 0x55, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x53, 0x70, 0x72, 0x65, 0x61, 0x64, 0x55,
	0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x49, 0x73, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x49, 0x73, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x65, 0x72, 0x22, 0x12,
	0x0a, 0x10, 0x54, 0x68, 0x65, 0x43, 0x68, 0x61, 0x72, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x3a, 0x0a, 0x11, 0x54, 0x68, 0x65, 0x43, 0x68, 0x61, 0x72, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x3e,
	0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x6f,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x54, 0x6f,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x8b,
	0x01, 0x0a, 0x1f, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x6d, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x69, 0x6d, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x4f, 0x6e, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x4f, 0x6e, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x77,
	0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x54, 0x77, 0x6f, 0x22, 0x3c, 0x0a, 0x20,
	0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x4b, 0x0a, 0x1d, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x32, 0x0a, 0x1e, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x72, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x72, 0x6c, 0x22, 0x4c, 0x0a, 0x20, 0x55,
	0x73, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x6c, 0x73, 0x49, 0x6e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x74, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x53, 0x74, 0x72, 0x22, 0x3d, 0x0a, 0x21, 0x55, 0x73, 0x65,
	0x72, 0x46, 0x69, 0x6c, 0x6c, 0x73, 0x49, 0x6e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0xa4, 0x04, 0x0a, 0x0c, 0x44, 0x69, 0x73,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x69, 0x0a, 0x16, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x26, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x61, 0x72,
	0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x6e,
	0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x72, 0x0a, 0x19, 0x55, 0x73, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x6c,
	0x73, 0x49, 0x6e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x29, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x46, 0x69, 0x6c, 0x6c, 0x73, 0x49, 0x6e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x61,
	0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x6c, 0x73,
	0x49, 0x6e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6f, 0x0a, 0x18, 0x44, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x53, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x12, 0x28, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x44,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29,
	0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x09, 0x54, 0x68, 0x65,
	0x43, 0x68, 0x61, 0x72, 0x74, 0x73, 0x12, 0x19, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x2e, 0x54, 0x68, 0x65, 0x43, 0x68, 0x61, 0x72, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x54, 0x68, 0x65, 0x43,
	0x68, 0x61, 0x72, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a,
	0x0a, 0x4c, 0x6f, 0x6f, 0x6b, 0x44, 0x6f, 0x6e, 0x65, 0x55, 0x70, 0x12, 0x18, 0x2e, 0x61, 0x72,
	0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x4c, 0x6f, 0x6f, 0x6b, 0x44, 0x6f, 0x6e, 0x65, 0x4f, 0x72,
	0x55, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e,
	0x4c, 0x6f, 0x6f, 0x6b, 0x44, 0x6f, 0x6e, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x3d, 0x0a, 0x06, 0x4c, 0x6f, 0x6f, 0x6b, 0x55, 0x70, 0x12, 0x18, 0x2e, 0x61, 0x72, 0x74,
	0x69, 0x63, 0x6c, 0x65, 0x2e, 0x4c, 0x6f, 0x6f, 0x6b, 0x44, 0x6f, 0x6e, 0x65, 0x4f, 0x72, 0x55,
	0x70, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x4c,
	0x6f, 0x6f, 0x6b, 0x44, 0x6f, 0x6e, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x52, 0x65, 0x73, 0x70, 0x42,
	0x10, 0x5a, 0x0e, 0x2e, 0x3b, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_distribution_proto_rawDescOnce sync.Once
	file_distribution_proto_rawDescData = file_distribution_proto_rawDesc
)

func file_distribution_proto_rawDescGZIP() []byte {
	file_distribution_proto_rawDescOnce.Do(func() {
		file_distribution_proto_rawDescData = protoimpl.X.CompressGZIP(file_distribution_proto_rawDescData)
	})
	return file_distribution_proto_rawDescData
}

var file_distribution_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_distribution_proto_goTypes = []any{
	(*LookDoneOrUpReq)(nil),                   // 0: article.LookDoneOrUpReq
	(*LookDoneOrUpResp)(nil),                  // 1: article.LookDoneOrUpResp
	(*UserList)(nil),                          // 2: article.UserList
	(*TheChartsRequest)(nil),                  // 3: article.TheChartsRequest
	(*TheChartsResponse)(nil),                 // 4: article.TheChartsResponse
	(*ListRank)(nil),                          // 5: article.ListRank
	(*DistributionLevelSettingRequest)(nil),   // 6: article.DistributionLevelSettingRequest
	(*DistributionLevelSettingResponse)(nil),  // 7: article.DistributionLevelSettingResponse
	(*GenerateInvitationCodeRequest)(nil),     // 8: article.GenerateInvitationCodeRequest
	(*GenerateInvitationCodeResponse)(nil),    // 9: article.GenerateInvitationCodeResponse
	(*UserFillsInInvitationCodeRequest)(nil),  // 10: article.UserFillsInInvitationCodeRequest
	(*UserFillsInInvitationCodeResponse)(nil), // 11: article.UserFillsInInvitationCodeResponse
}
var file_distribution_proto_depIdxs = []int32{
	2,  // 0: article.LookDoneOrUpResp.list:type_name -> article.UserList
	5,  // 1: article.TheChartsResponse.list:type_name -> article.ListRank
	8,  // 2: article.Distribution.GenerateInvitationCode:input_type -> article.GenerateInvitationCodeRequest
	10, // 3: article.Distribution.UserFillsInInvitationCode:input_type -> article.UserFillsInInvitationCodeRequest
	6,  // 4: article.Distribution.DistributionLevelSetting:input_type -> article.DistributionLevelSettingRequest
	3,  // 5: article.Distribution.TheCharts:input_type -> article.TheChartsRequest
	0,  // 6: article.Distribution.LookDoneUp:input_type -> article.LookDoneOrUpReq
	0,  // 7: article.Distribution.LookUp:input_type -> article.LookDoneOrUpReq
	9,  // 8: article.Distribution.GenerateInvitationCode:output_type -> article.GenerateInvitationCodeResponse
	11, // 9: article.Distribution.UserFillsInInvitationCode:output_type -> article.UserFillsInInvitationCodeResponse
	7,  // 10: article.Distribution.DistributionLevelSetting:output_type -> article.DistributionLevelSettingResponse
	4,  // 11: article.Distribution.TheCharts:output_type -> article.TheChartsResponse
	1,  // 12: article.Distribution.LookDoneUp:output_type -> article.LookDoneOrUpResp
	1,  // 13: article.Distribution.LookUp:output_type -> article.LookDoneOrUpResp
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_distribution_proto_init() }
func file_distribution_proto_init() {
	if File_distribution_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_distribution_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*LookDoneOrUpReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distribution_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*LookDoneOrUpResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distribution_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*UserList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distribution_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*TheChartsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distribution_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*TheChartsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distribution_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ListRank); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distribution_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DistributionLevelSettingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distribution_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*DistributionLevelSettingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distribution_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GenerateInvitationCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distribution_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*GenerateInvitationCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distribution_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*UserFillsInInvitationCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distribution_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*UserFillsInInvitationCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_distribution_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_distribution_proto_goTypes,
		DependencyIndexes: file_distribution_proto_depIdxs,
		MessageInfos:      file_distribution_proto_msgTypes,
	}.Build()
	File_distribution_proto = out.File
	file_distribution_proto_rawDesc = nil
	file_distribution_proto_goTypes = nil
	file_distribution_proto_depIdxs = nil
}
