NaCos:
  NameSpace: "6aeaab18-de35-4479-8bb5-53af4f3dca02"
  DataId: "retailers"
  Group: "retailers"
  Host: "14.103.150.223"
  Port: 8848
UserSrv:
  Host: "127.0.0.1"
  Port: 8081
ProductSrv:
  Host: "127.0.0.1"
  Port: 8082
OrderSrv:
  Host: "127.0.0.1"
  Port: 8083
UserEnterSrv:
  Host: "127.0.0.1"
  Port: 8084
ArticleSrv:
  Host: "127.0.0.1"
  Port: 8085
AdministratorsSrv:
  Host: "127.0.0.1"
  Port: 8086
CartSrv:
  Host: "127.0.0.1"
  Port: 8087
DistributionSrv:
  Host: "127.0.0.1"
  Port: 8088

RandomString:
  Log: 5


AliPay:
  APPID: "9021000142690924"
  NotifyURL: "https://5b621e20.r35.cpolar.top/api/c/order/alipay"
  ReturnURL: "https://www.baidu.com/"
  Key: "MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCVv83zHXboNkKoZDtecBzP+tCuBsYnnhArXMRGHfGRxfZcUJwF+oGB7fzueVLHdH3aGCUVXSTEvcRLdJweTM1JD3NXV2Le5a/h7/J7inW4UUZQO1ThpSAPYNQNkEdGpLirdmO1X0xgSSHdNnX35Qho9aVidJRQYQLNrd9+1SaC/8C90KSqA4M5s1Ikjg/B+SZpk2dwutQ5vIlgc9cuPggCqLpQT6W1aTmkSzaPivik3whysyOouaal4h3tjBev6cXeZZ2R9YGqJqntPa84xmnSDhKEvcjgGW65MsX89Y/+f+HVlccG9fBlEDK+xSdVsHwuUESnxrFxh3SMdChDZwbnAgMBAAECggEBAIWtReTbjZT3MwPtDc5c2GuUo4pmQ6eEAz0iP5e0DTwq8qQv1UfE+q0IzLv5E7s3M01oNlpe3n6+RCdzfhXSS4MHxtfWC02czigrsVM1I6cY7mKaxEf1xqvTrRg6jlXyn2N4eMOkwaJGRnOZtS9IhfxkJHHCTc9++iivKQ6oqgtPbdgAcuH8VFBV3NQ20PIzLryJRisYO4UnOR7R80QVXcoY1x73bp1cDBw6KmKu/zaVrhXq6nTueX/IzIMheYVxItbSgT8XEF6cRIkgjAaeFcuW+5oZvo80wjqf8gnw4SPI0yetRBzF11rsXPTAYUExCyy6uCjeWrplqmorNgvaoYkCgYEA6uQ5sjalc3Ave27N/SMCNiXf6qxuQNDu2+Utp1jgwzWUj4M/8dghKcekk7Ra9D9Hc+Z11n9Kb1vmRwLXgtM++EGZJpBYtVCH5RjIRGrC8o+OTP9kToUOO91gxR/b5Ph/MCGYgsROjO5DHL3HSHfpAu5vpnSQjRQvip5jhItKeDMCgYEAozTYuar1DIG6fyUFUvsVlTVwsP/ntb2WJsDkvsQQWKpXL8k0LDbRLm0NdQG7knFk7C0ERzT9yJDd4rSlcmypBD/c7k1lePGL9NuB/iJiOjI/iaeUikrtFioiUJDXwR5Zna5wXGtSuoApiy8hDWWEPdb1UPJCMwL8IZvhKSJOUn0CgYBR8Jen8aQ55vLJblfxbFsDJKc+KDS166zHjOUmMb0GnBRdE/4kka7P8lMZK5tnBQQaDFUjJHiE7FwifX1MqACZfdi9OTGY3qTpaIHETDIBh86uUZFeStAyVgHCAmElOQK1eaLIS07TnvJOfm2cfCgO27qbKKKcdGQ5SROSUz0BPQKBgQCdfwYWRpAr/ZUH1aYJqhvt3aBebtYgYFBiHYuhPHu51MhGaRhcAppi/wIZhA6LB7qo39hdDxpJTuORP1rZzVpdq3N81Fu0FwVEyf/sSyoXlx4RrRJ/UkbxOL/cl6pdxvgcXpY32aoAKGXu1xBCaVDwjFw4PVD9AUhm9pKWq3CB0QKBgQDodN5Qu6FLLBWq7jEk+cpoVglX1eb5r8hwm+t0es4yZRpZJ1x6Q0liUWqTwT3a6rPFn0CEvGhS47X03szZiYzscGrd49LYzAt5qE+BUbxJAzWEEqoHLBSKcU0wCYNGTTb/VkDjhFcngPrAI4g2MZ8nLuYJ/5ZNCq+i0+vb2EvQ5Q=="